-- OpsMemory — Migration 0023: relax users.role CHECK + migrate Kyle/Joanna.
--
-- Idempotent. NO top-level BEGIN/COMMIT — scripts/migrate.py owns
-- the outer transaction.
--
-- Phase MT-2: 0001 enforces CHECK (role IN ('admin', 'owner')) on
-- both users and business_memberships. We need users.role to also
-- accept 'platform_admin', but business_memberships.role must STAY
-- ('admin', 'owner') because per-business 'admin' is a separate
-- concept and platform_admin doesn't make sense at the membership
-- level.
--
-- This migration:
--   1. Drops the existing users.role CHECK constraint (if present).
--   2. Adds a new users_role_chk allowing platform_admin too.
--   3. UPDATE Kyle (...0101): admin -> platform_admin.
--   4. UPDATE Joanna (...0102): admin -> owner. She keeps her
--      business_memberships.role='admin' for borderline + redhot
--      (per-business admin authority preserved); the platform-wide
--      visibility leak (visible_business_ids returning None for
--      admin role) is closed.
--
-- The CHECK constraint on business_memberships is unchanged.
-- Constraint name is generated by Postgres at table create time;
-- we look it up dynamically since the 0001 migration didn't name it
-- explicitly.

DO $$
DECLARE
  cn text;
BEGIN
  SELECT conname INTO cn
  FROM pg_constraint
  WHERE conrelid = 'public.users'::regclass
    AND contype = 'c'
    AND pg_get_constraintdef(oid) ILIKE '%role%admin%owner%';
  IF cn IS NOT NULL THEN
    EXECUTE format('ALTER TABLE users DROP CONSTRAINT %I', cn);
  END IF;
END
$$;

-- 'service' deliberately excluded: service principals have their own
-- service_accounts table; users.role='service' was never used in
-- practice. The new CHECK keeps 'admin' so unmigrated rows don't
-- error out before the UPDATEs below run within this same migration.
ALTER TABLE users
  ADD CONSTRAINT users_role_chk
  CHECK (role IN ('platform_admin', 'admin', 'owner'));

-- Promote Kyle from admin -> platform_admin.
UPDATE users
SET role = 'platform_admin'::app_role,
    updated_at = now()
WHERE id = '00000000-0000-0000-0000-000000000101'::uuid
  AND role = 'admin'::app_role;

-- Demote Joanna from admin -> owner.
UPDATE users
SET role = 'owner'::app_role,
    updated_at = now()
WHERE id = '00000000-0000-0000-0000-000000000102'::uuid
  AND role = 'admin'::app_role;
